#!/usr/bin/env bash
set -ue

# this won't be set by xinitrc, so mock it based on this file's location

  DOTFILES="$(dirname "$0")"

# try to update first

  git submodule foreach "git checkout master; git pull origin"

# set up symlinks

  find "." -name "*.symlink" | egrep -v "\.git|/tmp/" | while read symlink; do
    symlink="${symlink##./}"
    linkable="$PWD/$symlink"
    basename="$(basename "$linkable" | sed 's/\.symlink$//')"

    if [[ -f "$linkable.sh" ]]; then
      target=$($linkable.sh)
    else
      target="$HOME/.$basename"
    fi

    if [[ -e "$target" ]] || [[ -L "$target" ]]; then
      if [[ "$(readlink "$target")" == "$linkable" ]]; then
        continue
      else
        mv -v "$target" "$target.bak"
      fi
    fi

    dirname="$(dirname "$target")"

    if [[ ! -d "$dirname" ]]; then
      mkdir -vp "$dirname"
    fi

    ln -vs "$linkable" "$target"
  done

# install fonts

  if [[ $(uname) == "Linux" ]]; then
    destination="$HOME/.fonts"
    method="/bin/ln -sv"
  elif [[ $(uname) == "Darwin" ]]; then
    destination="$HOME/Library/Fonts";
    method="/bin/cp -v"
  fi

  if [[ ! -z "$destination" ]]; then
    if [[ ! -d "$destination" ]]; then
      mkdir "$destination"
    fi

    for font in fonts/*; do
      basename=$(basename "$font")

      if [[ ! -f "$destination/$basename" ]]; then
        # don't quote $method because it includes switches
        $method "$PWD/$font" "$destination/$basename"
      fi
    done
  fi

# configure fonts

  if command -v infctl &> /dev/null; then
    infctl setstyle linux
  fi

# install system-wide ruby gems

  if command -v gem &> /dev/null; then
    xargs gem install --no-user-install < ruby/gems
  fi

# install system-wide npm packages

  if command -v npm &> /dev/null; then
    xargs npm install --global < node/packages
  fi

# update plugins

  vim +PlugUpdate +PlugInstall +qall

# download adblock files

  ./bin/update-adblock
