source $HOME/.vim/config/autocmd.vim
source $HOME/.vim/config/bindings.vim
source $HOME/.vim/config/bundle.vim
source $HOME/.vim/config/commands.vim
source $HOME/.vim/config/config.vim
source $HOME/.vim/config/functions.vim
source $HOME/.vim/config/plugin_config.vim
