source $DOTFILES/vim/config.vim
source $DOTFILES/vim/neobundle.vim

filetype plugin indent on
syntax on
colorscheme base16-default

source $DOTFILES/vim/autocmd.vim
source $DOTFILES/vim/bindings.vim
source $DOTFILES/vim/commands.vim
source $DOTFILES/vim/functions.vim
source $DOTFILES/vim/matchit.vim
source $DOTFILES/vim/plugin_config.vim
