#!/usr/bin/env fish

if test -d /etc/X11/xinit/xinitrc.d
  for node in /etc/X11/xinit/xinitrc.d/*
    if test -f $node
      . $node
    end
  end
end

if test -f $HOME/.Xmodmap; and which xmodmap > /dev/null
  xmodmap $HOME/.Xmodmap
end

if test -f $HOME/.Xresources
  xrdb -merge $HOME/.xresources
end

if test -d $HOME/.fonts
  xset +fp $HOME/.fonts
  xset fp rehash
  fc-cache
end

pgrep mpd -u $USER; or mpd
pgrep xautolock -u $USER; or xautolock -time 15 -locker slock -secure &

setxkbmap -option 'caps:escape'

eval (keychain --eval --clear)

exec dbus-launch --exit-with-session awesome
