#!/usr/bin/env zsh

# default, system-wide junk
if [[ -d "/etc/X11/xinit/xinitrc.d" ]]; then
  for node in /etc/X11/xinit/xinitrc.d/*; do
    if [[ -x "$node" ]]; then
      source "$node"
    fi
  done
  unset node
fi

# load our Xresources file
if [[ -f "$HOME/.Xresources" ]]; then
  xrdb -merge "$HOME/.Xresources"
fi

# xmodmap keyboard customizations
if [[ -f "$HOME/.Xmodmap" ]]; then
  xmodmap "$HOME/.Xmodmap"
fi

# if we've got a fonts folder, register it
if [[ -d "$HOME/.fonts" ]]; then
  xset +fp "$HOME/.fonts"
  xset fp rehash
  fc-cache
fi

# screen locking daemon
pgrep xautolock -u $USER || xautolock -time 30 -locker "slock" -secure &

# tap shift keys for parentheses
pgrep xcape || xcape -e "Shift_L=parenleft;Shift_R=parenright"

# local configuration
if [[ -e "$HOME/.xinitrc.local" ]]; then
  $HOME/.xinitrc.local
fi

# start the window manager
exec dbus-launch --exit-with-session awesome
