#!/usr/bin/env zsh

if [[ -d "/etc/X11/xinit/xinitrc.d" ]]; then
  for node in /etc/X11/xinit/xinitrc.d/*; do
    if [[ -x "$node" ]]; then
      source "$node"
    fi
  done
  unset node
fi

if [[ -f "$HOME/.Xresources" ]]; then
  xrdb -merge "$HOME/.Xresources"
fi

if [[ -d "$HOME/.fonts" ]]; then
  xset +fp "$HOME/.fonts"
  xset fp rehash
  fc-cache
fi

pgrep mpd -u $USER || mpd
pgrep xautolock -u $USER || xautolock -time 15 -locker "slock" -secure &

setxkbmap -option "caps:escape"

eval "$(keychain --eval --clear)"

exec dbus-launch --exit-with-session awesome
