#!/usr/bin/env zsh
set -ue

cd "$(tmux showenv "$(tmux display -p "TMUX_PWD_#D")" | cut -d= -f2-)"

format() {
  printf "#[fg=%s,bg=%s] %s " "$2" "$3" "$1"
}

git_trusted() {
  if git trusted; then
    printf "^"
  fi
}

git_status() {
  local status_text="$(git status)"
  if egrep "^# Untracked|^# Changed|^# Changes not" > /dev/null <<< "$status_text"; then
    printf "?"
  fi
  if grep "^# Changes to" > /dev/null <<< "$status_text"; then
    printf "\!"
  fi
  printf ' '
}

git_since() {
  local seconds="$(git since)"
  if [[ "$seconds" -gt 3600 ]]; then
    format "$((seconds / 3600))h$((seconds % 3600 / 60))m" "black" "red"
  elif [[ "$seconds" -gt 60 ]]; then
    format "$((seconds / 60))m" "black" "green"
  else
    format "<1m" "black" "green"
  fi
}

git_branch() {
  format "$(git branch | cut -d\  -f2)" "black" "white"
}

short_pwd() {
  format "$(pwd | sed "s#^$HOME#~#; s#\([a-zA-Z]\)[a-zA-Z]*[^/]*/#\1/#g")" "black" "blue"
}

if git root &> /dev/null; then
  git_trusted
  git_status
  git_since
  git_branch
fi

short_pwd
