#!/usr/bin/env zsh
set -ue

cd "$(tmux showenv "$(tmux display -p "TMUX_PWD_#D")" | cut -d= -f2-)"

format() {
  printf "#[fg=%s,bg=%s] %s " "$2" "$3" "$1"
}

git_status() {
  local s="$(git status)"
  local chars
  if git trusted; then
    chars="$chars^"
  fi
  if egrep "^# Untracked|^# Changed|^# Changes not" > /dev/null <<< "$s"; then
    chars="$chars?"
  fi
  if grep "^# Changes to" > /dev/null <<< "$s"; then
    chars="$chars!"
  fi
  if [[ -n "$chars" ]]; then
    format "$chars" "colour11" "colour3"
  fi
}

git_since() {
  local seconds="$(git since)"
  if [[ "$seconds" -gt 3600 ]]; then
    format "$((seconds / 3600))h$((seconds % 3600 / 60))m" "colour0" "colour9"
  elif [[ "$seconds" -gt 60 ]]; then
    format "$((seconds / 60))m" "colour11" "colour2"
  else
    format "<1m" "colour11" "colour2"
  fi
}

git_branch() {
  format "$(git rev-parse --abbrev-ref HEAD)" "colour11" "colour7"
}

short_pwd() {
  format "$(pwd | sed "s#^$HOME#~#; s#\([a-zA-Z]\)[a-zA-Z]*[^/]*/#\1/#g")" "colour0" "colour4"
}

if git root &> /dev/null; then
  git_status
  git_since
  git_branch
fi

short_pwd
