# set required environment variables
export DOTFILES="$HOME/.dotfiles"
export PATH=".git/trusted/../../bin:.git/trusted/../../.bundle/binstubs:$DOTFILES/bin:$HOME/.local/bin:/usr/local/bin:/usr/bin"

# source autoloaded zsh files
for thing in $DOTFILES/zsh/zshrc.d/*.zsh; do
  source $thing
done

# run chpwd hook on startup
chpwd
