#
# ~/.bash_profile
#

if [[ -f "~/.bashrc" ]]; then
  source ~/.bashrc
fi

export DOTFILES="$HOME/.dotfiles"
export PATH=".git/trusted/../../bin:.git/trusted/../../.bundle/binstubs:$DOTFILES/bin:$HOME/.local/bin:/usr/local/bin:/usr/bin"

export BROWSER="luakit"
export EDITOR="vim"

export LESSHISTFILE="/dev/null"
unset HISTFILE # disable bash_history

eval "$(keychain --eval --clear)"

if [[ -z "$DISPLAY" ]] && [[ "$XDG_VTNR" -gt 0 ]]; then
  exec startx
fi
